### ISSUE TITLE
No vegan option

### ISSUE THREAD

**Issue by STJEREM** [bash/baking#2]
Concerns #1

**Comment by bash** [comment]
NO.

**Comment by STJEREM** [comment]
Pinging @SirRade for a political debate.

**Comment by SirRade** [comment]
I find it unethical for an active member of our community to promote and endorse the inhumane treatment in light of lethal exploitations of defenseless farm animals.

As a visualization of the issue, I want to present you the discrepancy between the slaughter age of farm animals unfit for production (as their body becomes too stressed to continue production) versus their natural life expectancy, adapted in tabular form from Colleen etc all, 2012:

Dairy cow: 4-5 years on normal industrial milking, 18-25 years in the wild
Male offspring: 1.5 years as they cannot be used for dairy

Chicken: 1-4 years for industrial laying, 8 years for backyard laying, 13 years in the wild
Male offspring: 6 weeks as they cannot lay eggs

As you can clearly see, the purchase of eggs or dairy directly contributes to the slaughtering of millions of newborn animals that happen to have been born with the wrong gender every year. Their surviving mothers continue producing offspring and products until their body is exploited to a degree where it partially stops functioning, at which point they are discarded like used tools.

Endorsing this kind of animal treatment publicly on GitHub speaks volumes of sickish delusions about where ones food comes frosh, which is why I vote to either include vegan options or remove them all together.
